a= int(input('digite o primeiro numero'))
b= int(input('digite o segundo numero'))
c= int(input('digite o terceiro numero'))
ra=(a*2)*(b/2)
rb=(a*3)+(c)
rc=(c**3)
print('o produto do dobro do primeiro com metade do segundo é', ra)
print('a soma do triplo do primeiro com o terceiro é', rb)
print('o terceiro elevado ao cubo é', rc)
