print("Isso é uma calculadora de media")
num1 = int(input("Digite o primeiro numero"))
num2 = int(input("Digite o segundo numero"))
num3 = int(input("Digite o terceiro numero"))
num4 = int(input("Digite o quarto numero"))
result = int((num1 + num2 + num3 + num4)/4)
print(result)
